// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDutFDVKZXLiiFuyyqwshewP5HtkH6sd14',
    appId: '1:89903627525:web:dd70f816cd3a2a65aecb6c',
    messagingSenderId: '89903627525',
    projectId: 'laundry-app-891d5',
    authDomain: 'laundry-app-891d5.firebaseapp.com',
    storageBucket: 'laundry-app-891d5.firebasestorage.app',
    measurementId: 'G-DWEC88ZKSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWexVN3cqROBLm0E6iIRjeKsx1IsWa_o',
    appId: '1:89903627525:android:7555ef45e74a147aaecb6c',
    messagingSenderId: '89903627525',
    projectId: 'laundry-app-891d5',
    storageBucket: 'laundry-app-891d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1UMympqdVayr1mYy_3IdY7--DDvDGrl0',
    appId: '1:89903627525:ios:7ddcac9afd3ee5c8aecb6c',
    messagingSenderId: '89903627525',
    projectId: 'laundry-app-891d5',
    storageBucket: 'laundry-app-891d5.firebasestorage.app',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1UMympqdVayr1mYy_3IdY7--DDvDGrl0',
    appId: '1:89903627525:ios:7ddcac9afd3ee5c8aecb6c',
    messagingSenderId: '89903627525',
    projectId: 'laundry-app-891d5',
    storageBucket: 'laundry-app-891d5.firebasestorage.app',
    iosBundleId: 'com.example.laundryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDutFDVKZXLiiFuyyqwshewP5HtkH6sd14',
    appId: '1:89903627525:web:d0277d6c23c638a2aecb6c',
    messagingSenderId: '89903627525',
    projectId: 'laundry-app-891d5',
    authDomain: 'laundry-app-891d5.firebaseapp.com',
    storageBucket: 'laundry-app-891d5.firebasestorage.app',
    measurementId: 'G-0HEJXZXNQD',
  );
}
